version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"

  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000

volumes:
  db-data: